### ISSUE TITLE
Crash with window width <40

### ISSUE THREAD

**Issue by poleguy** [ckipp01/skan#100]
If you shrink the terminal window down to 39 columns or below, skan crashes and loses your work.
If you try to run skan in a window that's 39 columns or smaller it will not run and will show the same error.

Exception in thread "main" java.lang.IllegalArgumentException: count is negative: -1
	at java.base@19.0.2/java.lang.String.repeat(String.java:4422)
	at skan.ui.Board$.toListItem$1(Board.scala:81)
	at skan.ui.Board$.$anonfun$4(Board.scala:111)
	at scala.collection.ArrayOps$.map$extension(ArrayOps.scala:932)
	at skan.ui.Board$.render(Board.scala:111)
	at skan.project$package$.runBoard$1$$anonfun$1(project.scala:26)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at tui.Terminal.draw(Terminal.scala:84)
	at skan.project$package$.runBoard$1(project.scala:26)
	at skan.project$package$.run$$anonfun$1(project.scala:276)
	at scala.runtime.function.JProcedure2.apply(JProcedure2.java:15)
	at scala.runtime.function.JProcedure2.apply(JProcedure2.java:10)
	at tui.withTerminal$.apply(withTerminal.scala:16)
	at skan.project$package$.run(project.scala:276)
	at skan.run.main(project.scala:21)

**Comment by poleguy** [comment]
It has the same type of crash on windows 3 rows or less.
